[aws-origin]
type = s3
provider = Minio
access_key_id = origin-admin
secret_access_key = origin-secret
endpoint = http://origin:9000
env_auth = false

[azure-destination]
type = s3
provider = Minio
access_key_id = dest-admin
secret_access_key = dest-secret
endpoint = http://destination:9000
env_auth = false
