# Ejemplo: Pipeline de GitHub Actions para proyecto Web3
name: Smart Contract CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Hardhat tests
        run: npx hardhat test
        
      - name: Run Solidity coverage
        run: npx hardhat coverage
        
      - name: Run Slither analysis
        uses: crytic/slither-action@v0.3.0
        
  deploy-testnet:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy to Goerli
        run: npx hardhat run scripts/deploy.js --network goerli
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          
      - name: Verify contract on Etherscan
        run: npx hardhat verify --network goerli DEPLOYED_CONTRACT_ADDRESS "Constructor Arg"