{
 "title": "Demo App - Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests por segundo (success vs error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latencia promedio (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_request_duration_seconds_sum[1m]) / rate(app_request_duration_seconds_count[1m])",
     "legendFormat": "latencia_promedio"
    }
   ]
  },
  {
   "title": "Tasa de error (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * sum(rate(app_requests_total{status=\"error\"}[1m])) / sum(rate(app_requests_total[1m]))",
     "legendFormat": "error_rate"
    }
   ]
  }
 ]
}