global:
  resolve_timeout: 1m

route:
  receiver: demo-webhook
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m
  routes:
    - matchers:
        - severity="critical"
      receiver: demo-webhook
      continue: false

receivers:
  - name: demo-webhook
    webhook_configs:
      - url: "http://demo-app:9000/webhook"
        send_resolved: true
