services:
  localstack:
    image: localstack/localstack:3.4
    container_name: escalabilidad-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,autoscaling,cloudwatch,elbv2,iam,sts
      - DEBUG=0
    volumes:
      - "localstack-data:/var/lib/localstack"

volumes:
  localstack-data:
