[webservers]
web01 ansible_connection=docker ansible_python_interpreter=/usr/bin/python3 environment_name=blue
web02 ansible_connection=docker ansible_python_interpreter=/usr/bin/python3 environment_name=green

[webservers:vars]
ansible_user=root
http_port=80
