input {
  file {
    path => "/usr/share/logstash/sample-logs/access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    exit_after_read => true
  }
}

filter {
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
  }

  date {
    match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
  }

  mutate {
    convert => {
      "response" => "integer"
      "bytes" => "integer"
    }
    remove_field => ["timestamp", "message"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "elk-demo-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
